CREATE TABLE "SYSTEM"."CUSTOMER" 
    (
        CUSTOMER_ID      INT         GENERATED AS IDENTITY NOT NULL ,
        CUSTOMER_NAME     VARCHAR2(45) NOT NULL,
        PHONE INT,
        EMAIL    VARCHAR2(45) ,
        ADDRESS1 VARCHAR2(45) ,
        ADDRESS2 VARCHAR2(45) ,
        STATE VARCHAR2(45) ,
        ZIPCODE VARCHAR2(45),
        CREATEDBY VARCHAR2(45) NOT NULL,
        CREATEDDATE TIMESTAMP NOT NULL,
        UPDATEDBY VARCHAR2(45),
        UPDATEDDATE TIMESTAMP,
        PRIMARY KEY(CUSTOMER_ID)
    );

CREATE TABLE "SYSTEM"."ITEMDETAILS"
    (
        ITEM_ID   INT  GENERATED AS IDENTITY NOT NULL ,
        ITEM_NAME  VARCHAR2(100) NOT NULL,
        ITEM_PRICE DECIMAL NOT NULL,
        CREATEDBY VARCHAR2(100) NOT NULL,
        CREATEDDATE TIMESTAMP NOT NULL,
        UPDATEDBY VARCHAR2(100),
        UPDATEDDATE TIMESTAMP,
        PRIMARY KEY(ITEM_ID)
    );

    CREATE TABLE "SYSTEM"."INVENTORY"
    (
        INVENTORY_ID   INT  GENERATED AS IDENTITY NOT NULL ,
        ITEM_ID  VARCHAR2(100) NOT NULL,
        UNITS INT NOT NULL,
        CREATEDBY VARCHAR2(100) NOT NULL,
        CREATEDDATE TIMESTAMP NOT NULL,
        UPDATEDBY VARCHAR2(100),
        UPDATEDDATE TIMESTAMP,
        PRIMARY KEY(INVENTORY_ID)
    );

    CREATE TABLE "SYSTEM"."ORDERDETAILS"
    (
        ORDER_ID   INT  GENERATED AS IDENTITY NOT NULL ,
        CUSTOMER_ID  VARCHAR2(100) NOT NULL,
        ORDER_DATE TIMESTAMP NOT NULL,
        AMOUNT DECIMAL NOT NULL,
        REWARD_POINTS INT NULL,
        CREATEDBY VARCHAR2(100) NOT NULL,
        CREATEDDATE TIMESTAMP NOT NULL,
        UPDATEDBY VARCHAR2(100),
        UPDATEDDATE TIMESTAMP,
        PRIMARY KEY(ORDER_ID)
    );


    CREATE TABLE "SYSTEM"."ORDEREDITEMS"
    (
        ORDERED_ITEMS_ID   INT  GENERATED AS IDENTITY NOT NULL ,
        ORDER_ID  INT NOT NULL,
        ITEMID INT NOT NULL,
        QUANTITY INT NOT NULL,
        CREATEDBY VARCHAR2(100) NOT NULL,
        CREATEDDATE TIMESTAMP NOT NULL,
        UPDATEDBY VARCHAR2(100),
        UPDATEDDATE TIMESTAMP,
        PRIMARY KEY(ORDERED_ITEMS_ID)
    );

    ALTER TABLE "SYSTEM"."ORDERDETAILS" ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES "SYSTEM"."CUSTOMER"(CUSTOMER_ID);

    ALTER TABLE "SYSTEM"."ORDEREDITEMS" ADD FOREIGN KEY (ORDER_ID) REFERENCES "SYSTEM"."ORDERDETAILS"(ORDER_ID);
    
    ALTER TABLE "SYSTEM"."ORDEREDITEMS" ADD FOREIGN KEY (ITEMID) REFERENCES "SYSTEM"."ITEMDETAILS"(ITEM_ID);